//
//  Events.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Events: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _eventID: String?
    var _endDate: String?
    var _startDate: String?
    var _teamID: String?
    var _title: String?
    
    class func dynamoDBTableName() -> String {

        return "danceeventmanagerapp-mobilehub-1321329505-Events"
    }
    
    class func hashKeyAttribute() -> String {

        return "_eventID"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_eventID" : "eventID",
               "_endDate" : "endDate",
               "_startDate" : "startDate",
               "_teamID" : "teamID",
               "_title" : "title",
        ]
    }
    
    func getEventNameWithYear() -> String {
        let dateFormatter:DateFormatter = DateFormatter()
        dateFormatter.dateFormat = "yyyy"
        let stringToDate:Date = dateFormatter.date(from: self._startDate!)!
        let dateToString:String = dateFormatter.string(from: stringToDate)
        return "\(self._title!) \(dateToString)"
    }
    func setStartDateWithDateObject(date:Date) {
        let formatter = DateFormatter()
        formatter.dateFormat = "MM dd, yyyy"
        self._startDate = formatter.string(from: date)
    }
    
    func setEndDateWithDateObject(date:Date) {
        let formatter = DateFormatter()
        formatter.dateFormat = "MM dd, yyyy"
        self._endDate = formatter.string(from: date)
    }
}
