//
//  Events.swift
//  MySampleApp
//
//
// Copyright 2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Events: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _eventName: String?
    @objc var _startDate: String?
    @objc var _endDate: String?
    
    class func dynamoDBTableName() -> String {

        return "danceeventmanagerapp-mobilehub-1321329505-Events"
    }
    
    class func hashKeyAttribute() -> String {

        return "_eventName"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_startDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_eventName" : "eventName",
               "_startDate" : "startDate",
               "_endDate" : "endDate",
        ]
    }
    
    func setStartDateWithDateObject(date:Date) {
        let dateFormatter:DateFormatter = DateFormatter()
        dateFormatter.dateFormat = "MMM dd yyyy"
        self._startDate = dateFormatter.string(from: date)
    }
    
    func setEndDateWithDateObject(date:Date) {
        let dateFormatter:DateFormatter = DateFormatter()
        dateFormatter.dateFormat = "MMM dd yyyy"
        self._endDate = dateFormatter.string(from: date)
    }
    
    func getEventNameWithYear() -> String {
        let dateFormatter:DateFormatter = DateFormatter()
        dateFormatter.dateFormat = "MMM dd yyyy"
        let stringToDate:Date = dateFormatter.date(from: self._startDate!)!
        let yearString:String = "\(Calendar.current.component(.year, from: stringToDate))"
        let eventNameWithYear:String = "\(self._eventName!) \(yearString)"
        return eventNameWithYear
    }
}
